class elem():
    base_url = "https://opensource-demo.orangehrmlive.com/"
    list_url = "https://opensource-demo.orangehrmlive.com/web/index.php/admin/viewJobTitleList"
    dashboard_url = "https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index"
    jobtitle = "//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[2]/ul/li[1]"
    username = "//*[@id='app']/div[1]/div/div[1]/div/div[2]/div[2]/form/div[1]/div/div[2]/input"
    password = "//*[@id='app']/div[1]/div/div[1]/div/div[2]/div[2]/form/div[2]/div/div[2]/input"
    header = "//*[@id='app']/div[1]/div[1]/header/div[1]/div[1]/span/h6"
    menu_admin = "//*[@id='app']/div[1]/div[1]/aside/nav/div[2]/ul/li[1]/a"
    dropdown_job = "//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[2]"
    header_jobtitle = "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div[1]/h6"
    btn_login = "//*[@id='app']/div[1]/div/div[1]/div/div[2]/div[2]/form/div[3]/button"
    btn_add = "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div[1]/div/button"
    btn_edit = "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div[3]/div/div[2]/div[1]/div/div[4]/div/button[2]"
    btn_save = "//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[5]/button[2]"
    btn_hapus = "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div[3]/div/div[2]/div[1]/div/div[4]/div/button[1]"
    btn_yes_delete = "//*[@id='app']/div[3]/div/div/div/div[3]/button[2]"
    btn_cancelcreate = "//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[5]/button[1]"
    btn_cancelhapus = "//*[@id='app']/div[3]/div/div/div/div[3]/button[1]"
    btn_checkbox = "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div[3]/div/div[1]/div/div[1]/div/label/span"
    btn_checkbox2 = "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div[3]/div/div[2]/div[1]/div/div[1]/div"
    btn_delete_selected = "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div[2]/div/div/button"

    
    input_jobtitle = "//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[1]/div/div[2]/input"
    input_jobtitle2 = "//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[1]/div/div[2]/input"
    input_description = "//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[2]/div/div[2]/textarea"
    input_specification = "oxd-file-input"
    input_note = "//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[4]/div/div[2]/textarea"
    val_max = "//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[3]/div/span"

    #edit data
    edit_jobtitle = "//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[1]/div/div[2]/input"
    edit_description = "//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[2]/div/div[2]/textarea"
    edit_specification = "orangehrm-file-current"
    edit_note = "//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[4]/div/div[2]/textarea"
    validasi_required = "//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[1]/div/span"
    validasi_same = "//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[1]/div/span"

